# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-23 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='\u65e5\u671f')),
                ('hour', models.FloatField(verbose_name='\u5de5\u65f6')),
                ('content', models.TextField(max_length=2048, verbose_name='\u5de5\u4f5c\u5185\u5bb9')),
            ],
            options={
                'verbose_name_plural': '\u5de5\u4f5c\u65e5\u5fd7',
            },
        ),
        migrations.CreateModel(
            name='monthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256, verbose_name='\u59d3\u540d')),
                ('project', models.CharField(max_length=128, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('monthNum', models.CharField(max_length=256, verbose_name='\u6708\u4efd')),
                ('monthCycle', models.CharField(max_length=256, verbose_name='\u6708\u62a5\u65f6\u95f4')),
                ('monthWorkHour', models.TextField(max_length=10240, verbose_name='\u6708\u5de5\u65f6')),
            ],
            options={
                'verbose_name_plural': '\u6708\u62a5',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=128, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('remarks', models.TextField(blank=True, max_length=128, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name_plural': '\u9879\u76ee',
            },
        ),
        migrations.CreateModel(
            name='weekReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=256, verbose_name='\u59d3\u540d')),
                ('weekNum', models.CharField(max_length=256, verbose_name='\u5468\u6b21')),
                ('weekCycle', models.CharField(max_length=256, verbose_name='\u5468\u62a5\u65f6\u95f4')),
                ('lastWeekContent', models.TextField(max_length=10240, verbose_name='\u672c\u5468\u5de5\u4f5c\u8ba1\u5212')),
                ('thisWeekContent', models.TextField(max_length=10240, verbose_name='\u672c\u5468\u5de5\u4f5c\u5185\u5bb9')),
                ('nextWeekContent', models.TextField(max_length=10240, verbose_name='\u4e0b\u5468\u5de5\u4f5c\u8ba1\u5212')),
            ],
            options={
                'verbose_name_plural': '\u5468\u62a5',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Project', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
